### ISSUE TITLE
Parallelize bunch tracking in Tao using openMP

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#152]
- [x] Code
- [ ] Document (Section in Overview chapter started.)

**Comment by DavidSagan** [comment]
Initial try parallelizing at the single track1_bunch_hom level. I get about a factor of 2 speedup using 8 threads. Best guess is that there is a lot of overhead since threading is done separately for each element. 

- [ ] Is there a good way to parallelize over multiple elements? Must remember that CSR is not parallelized.
- [ ] Random number generation with radiation not properly handled.

**Comment by DavidSagan** [comment]
Parallelization done at Bmad level. Not sure best way to document so skip this for now.
