### ISSUE TITLE
Implement reverse time tracking.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#174]
Right now a lattice can be reversed but tracking remains in the forward direction.

Parameter interpretation when tracking backwards in time:
* px, py are momenta as seen with forward time.
* orbit%direction is the direction to track a particle. For example, for backwards time tracking and %direction = 1, the particle is tracked in the +s direction with time going backwards. That is, the particle is actually moving in the -s direction in forward time.

To Do:
- [ ]  Parameter exists: bmad_com%backwards_time_tracking but is not used and not documented
- [ ] Regression tests. Especially electric and RF elements.
- [ ] Document

Possible routines to modify:

- [ ] code/convert_particle_coordinates_s_to_t.f90
- [ ] code/convert_particle_coordinates_t_to_s.f90
- [ ] code/lat_sanity_check.f90
- [ ] code/make_mat6.f90
- [ ] code/multipole_spin_tracking.f90
- [ ] code/offset_particle.f90
- [ ] code/particle_is_moving_backwards.f90
- [ ] code/particle_is_moving_forward.f90
- [ ] code/pointers_to_attribute.f90
- [ ] code/reference_energy_correction.f90
- [ ] code/rotate_spin_a_step.f90
- [ ] code/solenoid_track_and_mat.f90
- [ ] code/track1.f90
- [ ] code/track_many.f90
- [ ] code/write_lattice_in_foreign_format.f90
- [ ] custom/apply_element_edge_kick_hook.f90
- [x] geometry/orbit_to_local_curvilinear.f90
- [x] hdf5/hdf5_write_beam.f90
- [ ] interface/ptc_interface_mod.f90
- [ ] low_level/apply_element_edge_kick.f90
- [ ] low_level/calc_next_fringe_edge.f90
- [ ] low_level/check_aperture_limit.f90
- [ ] low_level/distance_to_aperture.f90
- [ ] low_level/init_fringe_info.f90
- [ ] low_level/make_mat6_bmad.f90
- [ ] low_level/make_mat6_symp_lie_ptc.f90
- [ ] low_level/multipole_kick_mat.f90
- [ ] low_level/rf_coupler_kick.f90
- [ ] low_level/track1_bmad.f90
- [ ] low_level/track1_linear.f90
- [ ] low_level/track1_runge_kutta.f90
- [ ] low_level/track1_spin_bmad.f90
- [ ] low_level/track1_taylor.f90
- [ ] low_level/track1_time_runge_kutta.f90
- [ ] low_level/track_a_bend.f90
- [x] low_level/track_a_drift.f90
- [ ] low_level/track_a_patch.f90
- [ ] low_level/track_a_quadrupole.f90
- [ ] low_level/track_a_sad_mult.f90
- [ ] low_level/track_a_sol_quad.f90
- [ ] low_level/track_a_thick_multipole.f90
- [ ] modules/coord_mod.f90
- [ ] modules/em_field_mod.f90
- [ ] modules/equality_mod.f90
- [ ] modules/fringe_mod.f90
- [ ] modules/multipole_mod.f90
- [ ] modules/runge_kutta_mod.f90
- [ ] modules/symp_lie_mod.f90
- [ ] modules/time_tracker_mod.f90
- [ ] modules/wall3d_mod.f90
- [ ] multiparticle/beam_utils.f90
- [ ] multiparticle/track_bunch_time.f90
- [ ] photon/track1_bmad_photon.f90
- [ ] photon/track1_photon_mod.f90
- [ ] Tao/tao_show_mod.f90

**Comment by DavidSagan** [comment]
Backwards time devel now in issue #1637.
