### ISSUE TITLE
Implement linear spin/orbit "sprint" tracking.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#178]
To do:
- [x] Add ele%spin_taylor_ref_orb_in(6) vector component.
- [x] Set  ele%spin_taylor_ref_orb_in in ele_to_taylor.
- [x] Add to spin_taylor_to_linear arg list taylor_ref_orb and linear_ref_orb
- [x] Add call to spin_taylor_to_linear in make_mat6_symp_lie_ptc.
- [x] Modify track1_taylor to use spin_taylor_to_linear
- [x] Create: bmad/low_level/track1_spin_sprint.f90 to calculate ele%spin_taylor
- [x] Create: bmad/spin/ele_to_spin_sprint.f90. Make sure this handles misalignments.
- [ ] Implement spin/orbit map concatenation: (Existing spin_concat_linear_maps -> ptc_spin_concat_linear_maps.)
- [ ] Implement PTC c_linear to spin_orbit_map1_struct converter (?)
- [ ] Make sure that offset_particle handles spin matrix but only if map_with_offsets is True.
- [ ] Document sprint tracking.
- [ ] New regression test: spin_map_test with map_with_offsets = T/F.
- [ ] Check that tracking_method_test is OK with map_with_offsets = F
- [ ] Add to mat6_calc_method_test regression: 1st order spin map output.
- [ ] Check backwards tracking
- [ ] Right now switching between sprint and taylor spin tracking does not remake ele%spin_taylor.

**Comment by DavidSagan** [comment]
Done.
