### ISSUE TITLE
Backwards time tracking needed

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#331]
For the space charge calc, to track a bunch from constant t to constant s or vice versa requires backwards time tracking. 

- [ ] Check bend fringes.
- [ ] Check electric and magnetic multipoles
- [ ] Check all element types

**Comment by DavidSagan** [comment]
Problem areas at this point in time:
```
"SAD_MULT2: Bmad_Standard-Merit"             ABS 1E-13  7.5848320000E-04
"SBEND1: Bmad_Standard-Merit"             ABS 1E-13  1.2946305773E-06
"LCAVITY1: Bmad_Standard-Merit"             ABS 1E-13  1.2381885501E-06

```

**Comment by DavidSagan** [comment]
@ColwynGulliford: Attached is a modified space_charge_mod.f90 file. If you want to test if this solves your problem, update to the latest bmad and use the attached file in place of the one in bmad/space_charge. Otherwise this will wait until Ningdong gets back.

@ChristopherMayes

[space_charge_mod.zip](https://github.com/DavidSagan/Bmad/files/11013592/space_charge_mod.zip)

**Comment by ColwynGulliford** [comment]
Will report shortly.

**Comment by ColwynGulliford** [comment]
I tried this but get thousands of errors, all of the form:

```
[ERROR | 2023-MAR-21 12:01:30] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
    TRACKING THROUGH ELEMENT: MG.PIP03#2 (22)
[ERROR | 2023-MAR-21 12:01:30] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
    TRACKING THROUGH ELEMENT: MG.MAR.END (23)
[ERROR | 2023-MAR-21 12:01:30] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
```

This happens after going to my bmad directory, doing "svn update *", and then replacing the file with the one you provide.  I then compile.

**Comment by DavidSagan** [comment]
@ColwynGulliford Please post your input files. Thanks.

**Comment by ColwynGulliford** [comment]
[mwe.tgz](https://github.com/DavidSagan/Bmad/files/11032485/mwe.tgz)

**Comment by ColwynGulliford** [comment]
Btw, I just came back to the machine I was testing that on, and I had a warning about "Out of Memory", I think due to the above issue.  In order to get back to normal I had to force quit the terminal Tao was running in (it was till printing those error messages).

**Comment by DavidSagan** [comment]
@ColwynGulliford Fixed these problems. Please update to the latest code and test.

**Comment by DavidSagan** [comment]
Closing.
