### ISSUE TITLE
Revamp exact dipole bend tracking to avoid low bend strength singularities

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#62]
Problem: The exact dipole bend tracking is derived from formulas from Etienne's "Beam Dynamics" book. These equations are singular (0/0 evaluations) when the bend strength is near zero. 

Solution: Rewrite the equations in terms of arcsin(x)/x and implement this special function.

- [x] Writeup procedure
- [x] Implement in Bmad
- [x] Implementation needs to be such that a particle entering on the zero orbit leaves on the zero orbit. For test optics can use lattice in tao/examples/optics_matching.
- [x] Rewrite exact fringe routine
- [ ] Publish results

**Comment by DavidSagan** [comment]
Done.
